website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import Note, SearchForm, Prod
from . import db
import json
from datetime import datetime
import mysql.connector


views = Blueprint("views", __name__)  # uycie wcześniejszego blueprinta


@views.route("/")
def home():
    return render_template("home.html", user=current_user)


# notatki
@views.route("/notes", methods=["POST", "GET"])
@login_required  # wymaga bycia zalogowanym
def notes():
    if request.method == "POST":
        title = request.form.get("title")
        note = request.form.get("note")  # Bierze note i title z htmla
        title = title.capitalize()
        if len(note) < 1:
            flash("Note is too short!", category="error")
        if len(title) < 1:
            flash("Title is too short!", category="error")
        else:
            new_note = Note(
                data=note, user_id=current_user.id, title=title
            )  # wsadzam dane do wczesniej przygotowanego modelu eby potem poszło do bazy naych
            db.session.add(new_note)  # Dodawanie notatki do bazy danych
            db.session.commit()
            flash("Note added!", category="success")

    return render_template("notes.html", user=current_user)


# miejsce na kalulator
@views.route("/calc", methods=["POST", "GET"])
def calc():
    return render_template("calc.html", user=current_user)


# zamówienia
@views.route("/orders", methods=["POST", "GET"])
@login_required
def orders():
    if request.method == "POST":
        prod = request.form.get("prod_name")  # Bierze  produkt z htmla
        prod_to_delete = Prod.query.filter_by(food=prod).all()

        for product in prod_to_delete:
            db.session.delete(product)
        db.session.commit()

        flash("Product deleted!", category="success")
        return redirect("/orders")
    else:
        prod = Prod.query

        sum_of_prod = (
            {}
        )  # dict w którym bede trzymać wszystkie produkty ale tylko raz i sumując ile ich łącznie jest

        for product in prod:  # tą petla wsadzam rzeczy do dicta sum_of_prod
            if product.food in sum_of_prod:
                sum_of_prod[product.food] += product.qty
            else:
                sum_of_prod[product.food] = product.qty
        return render_template(
            "orders.html", user=current_user, prod=prod, sum_of_prod=sum_of_prod
        )


@views.route("/delete-note", methods=["POST"])  # do usuwania notatek
def delete_note():
    note = json.loads(
        request.data
    )  # ładuje dane wysłane wczesniej przez JS z notes.html
    noteId = note["noteId"]  # pobieram id z htmla
    note = Note.query.get(noteId)  # a teraz wyszukuje na podstawie tego id w modelu
    if note:
        if (
            note.user_id == current_user.id
        ):  # usuwam tylko jeeli id usera i current usera sie zgadza
            db.session.delete(note)  # usuwam
            db.session.commit()
    return jsonify({})  # musze tak zwrócić chyba dlatego ę to potem znowu do JSa idzie


@views.route(
    "/delete-order", methods=["POST"]
)  # tak samo jak z notatkami tylko na produkcie dla jednego zamówienia a nie eby usunąć wszystkie
def delete_order():
    prod = json.loads(request.data)
    prodId = prod["prodId"]
    prod = Prod.query.get(prodId)
    if prod:
        db.session.delete(prod)
        db.session.commit()
    return jsonify({})


@views.route(
    "/edit_note/<int:id>", methods=["POST", "GET"]
)  # tu edituje notatki i uywam do tego id w linku
@login_required
def get_note(id):
    old_note = Note.query.get_or_404(id)  # biore notatke na podstawie id
    if old_note:
        if old_note.user_id == current_user.id:
            old_title = old_note.title  # rozdzielam sobie
            old_data = old_note.data
            old_date = old_note.date_now
            if request.method == "POST":
                title = request.form.get("title")
                note_text = request.form.get("note")
                title = title.capitalize()
                if len(note_text) < 1:
                    flash("Note is too short!", category="error")
                if len(title) < 1:
                    flash("Title is too short!", category="error")
                else:
                    db.session.delete(old_note)  # usuwam starą notatkę
                    new_note = Note(
                        data=note_text,
                        user_id=current_user.id,
                        title=title,
                        id=old_note.id,
                        date_now=old_date,
                    )  # ustalam jakie dane ma mieć nowa notatka, zostawiając stare id
                    db.session.add(new_note)  # dodaję nową notatkę
                    db.session.commit()
                    flash("Note edited!", category="success")
                    return redirect(url_for("views.get_note", id=new_note.id))

            return render_template(
                "edit_note.html",
                note=old_note,
                user=current_user,
                title=old_title,
                data=old_data,
            )


@views.context_processor
def base():
    form = SearchForm()
    return dict(form=form)


@views.route("/search", methods=["POST", "GET"])
def search():
    form = SearchForm()
    notes = Note.query
    user = current_user

    if form.validate_on_submit():
        searched = form.searched.data
        notes = notes.filter(
            Note.data.like("%" + searched + "%")
        )  # wyszukuje notatke taka która jest podobna
        notes = notes.filter(Note.user_id == user.id)  # eby sie zgadzało id
        notes = notes.order_by(Note.id).all()  # ustalam jaki order

        if len(searched) < 1:
            flash("Search cant be empty", category="error")
        else:
            return render_template(
                "search.html", form=form, searched=searched, user=user, notes=notes
            )


@views.route("/menu", methods=["POST", "GET"])
def menu():
    if request.method == "POST":
        qty = request.form.get("qty")
        prod = request.form.get("prod_name")  # Bierze qty i produkt z htmla
        if qty == None:
            flash("Quantity cant be empty", category="error")
        if int(qty) < 1:
            flash("Quantity cant be smaller than 1", category="error")
        else:
            new_ord = Prod(qty=qty, food=prod)
            db.session.add(new_ord)  # Dodawanie notatki do bazy danych
            db.session.commit()
            flash("Product added!", category="success")
    return render_template("menu.html", user=current_user)

website/templates/calc.html
{% extends "navbar.html" %}
{% block title %}
<title>Calc</title>
{% endblock %}
{% block content %}
<h1> Calc </h1>


{% endblock %}

website/templates/edit_note.html
{% extends "navbar.html" %}
{% block title %}
<title>Edit Note</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="/static/css/my_forms.css" />
<!--   nastepnym razem mona uyc modal z bootstrapa do notatek całkiem ładne rozwiązanie    --> 
<div class="text-center">
  <h1 >Edit note</h1>
  <form method="POST">
    <div class="text-center">
      <h3>
        <input for="exampleFormControlInput1" name="title" id="title" value={{ note.title }}>
      </h3>
        <textarea class="my_forms_area" name="note" id="note">{{ note.data }}</textarea>
        
    </div>
    <button type="submit" class="btn btn-success">Edit Note</button>
    <button type="button" class="btn btn-danger" onClick="deleteNote({{ note.id}})">Delete</button>
</form>
  <br>

  </div>
</div>




<script type="text/javascript">
    function deleteNote(noteId) {
        fetch("/delete-note", {
            method: "POST",
            body: JSON.stringify({ noteId: noteId }),
        }).then((_res) => {
            window.location.href = "/notes";
        });
    }

</script>

{% endblock %}

website/templates/home.html
{% extends "navbar.html" %}
{% block title %}
<title>Home</title>
{% endblock %}
{% block content %}
<h1> Home </h1>


{% endblock %}

website/templates/login.html
{% extends "navbar.html" %}
{% block title %}
<title>Log In</title>
{% endblock %}
{% block content %}
<link rel="stylesheet" href="/static/css/my_forms.css" />

<form method="POST" class="my_forms_area">
    <div class="alert alert-primary" role="alert">
        For demonstration purposes use email: admin@admin.com and password: admin
      </div>
    <h1 class="text-center">Log In</h1>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
    </div>
    <br>
    <button class="btn btn-primary" type="submit">Log In</button>
</form>


{% endblock %}

website/templates/menu.html
{% extends "navbar.html" %}
{% block title %}
<title>Menu</title>
{% endblock %}
{% block content %}
<div class="alert alert-danger" role="alert">
  Sometimes there can be a problem with overload of the website. All you need to do is refresh the website. :)
</div>
<h1 class="text-center"> Select what we need to order </h1>

<link rel="stylesheet" href="/static/css/my_forms.css" />


<div class="my_menu_area">
  <div class="row row-cols-1 row-cols-md-4 g-4">
    <form method="POST">
    <div class="col">
      <div class="card" style="width: 18rem;">
        <img src="/static/images/grander.png" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title" >Grander</h5>
          <p class="card-text">Premium chicken sandwich.</p>
        </div>
        
        <div class="card-body">
          <div class="text-end">
            <h6 class="card-text">Suppliers price: 20zł</h6>
            <div class="input-group">
              <input type="hidden" name="prod_name" value="Grander">
              <input type="number" class="form-control" placeholder="Quantity" aria-label="qty" value="1" name="qty" >
              <button type="submit" class="btn btn-success">Add to needed</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>

  <form method="POST">
    <div class="col">
      <div class="card" style="width: 18rem;">
        <img src="/static/images/zinger.png" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Zinger</h5>
          
          <p class="card-text">Lower quality chicken sandwich.</p>
        </div>
        
        <div class="card-body">
          <div class="text-end">
            <h6 class="card-text">Suppliers price: 15zł</h6>
            <div class="input-group">
              <input type="hidden" name="prod_name" value="Zinger">
              <input type="number" class="form-control" placeholder="Quantity" name="qty" value="1">
              <button type="submit" class="btn btn-success">Add to needed</button>
            </div>
            </div>
        </div>      
      </div>
    </div>
  </form>

  <form method="POST">
    <div class="col">
      <div class="card" style="width: 18rem;">
        <img src="/static/images/ramen.png" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Ramen Tantanmen</h5>
          <p class="card-text">The tastiest ramen.</p>
        </div>
        
        <div class="card-body">
          <div class="text-end">
            <h6 class="card-text">Suppliers price: 40zł</h6>
            <div class="input-group">
              <input type="hidden" name="prod_name" value="Ramen Tantanmen">
              <input type="number" class="form-control" placeholder="Quantity" name="qty" value="1">
              <button type="submit" class="btn btn-success">Add to needed</button>
            </div>
            </div>
        </div>
      </div>
    </div>
  </form>

  <form method="POST">
    <div class="col">
      <div class="card" style="width: 18rem;">
        <img src="/static/images/fries.webp" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Fries</h5>
          <p class="card-text">McDonald's style fries.</p>
        </div>
        
        <div class="card-body">
          <div class="text-end">
            <h6 class="card-text">Suppliers price: 10zł</h6>
            <div class="input-group">
              <input type="hidden" name="prod_name" value="Fries">
              <input type="number" class="form-control" placeholder="Quantity" name="qty" value="1">
              <button type="submit" class="btn btn-success">Add to needed</button>
            </div>
            </div>
        </div>
      </div>
    </div>
  </form>

  <form method="POST">
    <div class="col">
      <div class="card" style="width: 18rem;">
        <img src="/static/images/mtndew.png" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Mountain Dew Baja Blast</h5>
          <p class="card-text">The biggest abomination.</p>
        </div>
        
        <div class="card-body">
          <div class="text-end">
            <h6 class="card-text">Suppliers price: 100zł</h6>
            <div class="input-group">
              <input type="hidden" name="prod_name" value="Mountain Dew Baja Blast">
              <input type="number" class="form-control" placeholder="Quantity" name="qty" value="1">
              <button type="submit" class="btn btn-success">Add to needed</button>
            </div>
            </div>
        </div>
      </div>
    </div>
  </form>

  <form method="POST">
    <div class="col">
      <div class="card" style="width: 18rem;">
        <img src="/static/images/fiji.webp" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Fiji Water</h5>
          <p class="card-text">Terrible water, way too overpriced.</p>
        </div>
        
        <div class="card-body">
          <div class="text-end">
            <h6 class="card-text">Suppliers price: 10zł</h6>
            <div class="input-group">
              <input type="hidden" name="prod_name" value="Fiji Water">
              <input type="number" class="form-control" placeholder="Quantity" name="qty" value="1">
              <button type="submit" class="btn btn-success">Add to needed</button>
            </div>
            </div>
        </div>
      </div>
    </div>
  </form>

  <form method="POST">
    <div class="col">
      <div class="card" style="width: 18rem;">
        <img src="/static/images/cola.webp" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Coca-Cola Quebec Maple</h5>
          <p class="card-text">Actually great cola.</p>
        </div>
        
        <div class="card-body">
          <div class="text-end">
            <h6 class="card-text">Suppliers price: 15zł</h6>
            <div class="input-group">
              <input type="hidden" name="prod_name" value="Coca-Cola Quebec Maple">
              <input type="number" class="form-control" placeholder="Quantity" name="qty" value="1">
              <button type="submit" class="btn btn-success">Add to needed</button>
            </div>
            </div>
        </div>
      </div>
    </div>
  </form>

  <form method="POST">
    <div class="col">
      <div class="card" style="width: 18rem;">
        <img src="/static/images/root.png" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Root Beer</h5>
          <p class="card-text">Well I love it but I forgot the name of the other better root beer.</p>
        </div>
        
        <div class="card-body">
          <div class="text-end">
            <h6 class="card-text">Suppliers price: 10zł</h6>
            <div class="input-group">
              <input type="hidden" name="prod_name" value="Root Beer">
              <input type="number" class="form-control" placeholder="Quantity" name="qty" value="1">
              <button type="submit" class="btn btn-success">Add to needed</button>
            </div>
            </div>
        </div>
      </div>
    </div>
  </form>
  </div>

  

</div>


{% endblock %}

website/templates/navbar.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
    <title>Homepage</title>
    {% endblock title%}
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand"  href="/menu">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/notes">Notes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/orders">Orders</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/logout" style="color:rgb(255, 208, 0);">Log Out</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="/menu">To order</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/login">Log in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/signup">Sign up</a>
              </li>
              
              {% endif %}
            </ul>
            {% if user.is_authenticated %}
            <form class="d-flex" role="search" method="POST" action="{{ url_for('views.search') }}">
              {{ form.hidden_tag() }}
              <input class="form-control me-2" type="search" placeholder="Search notes" aria-label="Search" name="searched">
              <button class="btn btn-outline-warning" type="submit" >Search</button>
            </form>
            {% endif %}
          </div>
        </div>
      </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <div class="alert alert-danger d-flex align-items-center" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% else %}
                    <div class="alert alert-success d-flex align-items-center"  role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
        <div> 
        {% block content %}
        
        {% endblock %}
        </div>
      <br>
      <div class="text-center">
        
          <a href="https://www.facebook.com"><img type="button" src="{{ url_for('static', filename='images/facebook.png') }}" height="50px" width="50px"></a>
          <a href="https://www.instagram.com"><img type="button" src="{{ url_for('static', filename='images/instagram.png') }}" height="50px" width="50px"></a>
          <a href=""><img type="button" src="{{ url_for('static', filename='images/linkedin.png') }}" height="50px" width="50px"></a>
        
</body>
</html>

website/templates/notes.html
{% extends "navbar.html" %}
{% block title %}
<title>Notes</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="/static/css/my_forms.css" />
<!--   nastepnym razem mona uyc modal z bootstrapa do notatek całkiem ładne rozwiązanie    --> 
<div class="text-center">
  <h1 >Notes</h1>
  <form method="POST">
    <div class="text-center">
      <h3>
        <input placeholder="Tytuł" name="title" id="title">
      </h3>
        <textarea class="my_forms_area" placeholder="Tu wpisz notatke" name="note" id="note"></textarea>
        
    </div>
    <button type="submit" class="btn btn-primary">Add Note</button>
</form>
  <br>
  <div class="my_forms_area">
    {% for note in user.notes %}
      <ul class="list-group" id="notes">
          <h3 >
            <li class="list-group-item">{{ note.title }} </li>
          </h3>
          <li class="list-group-item">{{ note.data }} 
            <h6 class="text-end">{{ note.date_now.day }}-{{ note.date_now.month }}-{{ note.date_now.year }} {{ note.date_now.hour }}:{{ note.date_now.minute }} 
            <h6 class="text-end">
                <a href="{{ url_for('views.get_note', id=note.id)}}"><button type="button" class="btn btn-success"  >Edit</button></a>
                <button type="button" class="btn btn-danger" onClick="deleteNote({{ note.id}})">Delete</button>
                
            </h6>
          </h6>
        
          
        </ul>
        <br>
        <br>
        {% endfor %}
        
    </div>
  </div>
</div>




<script type="text/javascript">
    function deleteNote(noteId) {
        fetch("/delete-note", {
            method: "POST",
            body: JSON.stringify({ noteId: noteId }),
        }).then((_res) => {
            window.location.href = "/notes";
        });
    }
</script>

{% endblock %}

website/templates/orders.html
{% extends "navbar.html" %}
{% block title %}
<title>Orders</title>
{% endblock %}
{% block content %}
<h1 class="text-center"> How many to order </h1>

{% for x in sum_of_prod %}
<form method="POST">
<input type="hidden" name="prod_name" value="{{ x }}" >
&nbsp;Sum of {{x }}s to order: {{sum_of_prod[x]}} <button type="submit" class="btn btn-warning" >Product ordered/Not needed</button>
<br>
<br>
</form>
{% endfor %}
<br>




<div class="text-center">  
  <ul class="list-group list-group-flush">
    {% for product in prod %}
    <li class="list-group-item">{{ product.qty }} {{ product.food }}  <button type="button" class="btn btn-danger" onClick="deleteOrder({{ product.id }})">Delete one order</button></li>
    {% endfor %}
  </ul>
</div>


        

        
        <script type="text/javascript">
          function deleteOrder(prodId) {
              fetch("/delete-order", {
                  method: "POST",
                  body: JSON.stringify({ prodId: prodId }),
              }).then((_res) => {
                  window.location.href = "/orders";
              });
          }

          
        </script>
{% endblock %}

website/templates/search.html
{% extends "navbar.html" %}
{% block title %}
<title>Searched</title>
{% endblock %}

{% block content %}
<br>
<div class="text-center">
<h2> You searched for</h2>
<p>{{ searched }}</p>
    <h2>Your results</h2>


    
        <ul class="list-group list-group-flush" id="notes">
            {% for note in notes %}
            <li class="list-group-item">{{ note.data }}
              <h6 class="text-end">
                <a href="{{ url_for('views.get_note', id=note.id)}}"><button type="button" class="btn btn-success">Edit</button></a>
                <button type="button" class="btn btn-danger" onClick="deleteNote({{ note.id}})">Delete</button>
            </h6>
        
            </li>
            
            {% endfor %}
        </ul>
    </div>







    <script type="text/javascript">
        function deleteNote(noteId) {
    fetch("/delete-note", {
      method: "POST",
      body: JSON.stringify({ noteId: noteId }),
    }).then((_res) => {
      window.location.href = "/notes";
    });
    }
  </script>

    
{% endblock %}

website/templates/signup.html
{% extends "navbar.html" %}
{% block title %}
<title>Sign Up</title>
{% endblock %}
{% block content %}
<link rel="stylesheet" href="/static/css/my_forms.css" />
<form method="POST" class="my_forms_area"> 
    <h1 class="text-center">Sign Up</h1>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="firstname">First Name</label>
        <input type="text" class="form-control" id="firstname" name="firstname" placeholder="Enter First Name">
    </div>
    <div class="form-group">
        <label for="lastname">Last Name</label>
        <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Enter Last Name">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
    </div>
    <div class="form-group">
        <label for="password2">Password Confirm</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Enter password again">
    </div>
    <br>
    <button class="btn btn-primary" type="submit">Sign In</button>
</form>


{% endblock %}

website/templates/test.html
<h1> welcome</h1>